
  
  export const stateOptions = [
    { value: 'AL', label: 'Alabama', color: '#00B8D9', isFixed: true },
    { value: 'AK', label: 'Alaska', color: '#0052CC', isDisabled: true },
    { value: 'AS', label: 'American Samoa', color: '#5243AA', isFixed: true},
    { value: 'AZ', label: 'Arizona', color: '#1dd3bd'},
    { value: 'AR', label: 'Arkansas',color: '#FF8B00' },
    { value: 'CA', label: 'California', color: '#666666' },
    { value: 'CO', label: 'Colorado',color: '#FF8B00' },
    { value: 'CT', label: 'Connecticut', color: '#FFC400' },
    { value: 'DE', label: 'Delaware',  color: '#36B37E' },
    { value: 'DC', label: 'District Of Columbia',color: '#FF8B00' },
    { value: 'FM', label: 'Federated States Of Micronesia', color: '#36B37E' },
    { value: 'FL', label: 'Florida', color: '#FFC400' },
    { value: 'GA', label: 'Georgia', color: '#7fdbda' },
    { value: 'GU', label: 'Guam',color: '#00875A' },
    { value: 'HI', label: 'Hawaii', color: '#0052CC' },
    { value: 'ID', label: 'Idaho', color: "#fe91ca" },
    { value: 'IL', label: 'Illinois',color: '#00875A' },
    { value: 'IN', label: 'Indiana',color: '#fa26a0' },
    { value: 'IA', label: 'Iowa', color: '#24a19c'},
    { value: 'KS', label: 'Kansas', color: '#0052CC' },
    { value: 'KY', label: 'Kentucky', color: '#FF5630' },
    { value: 'LA', label: 'Louisiana', color: '#7fdbda' },
    { value: 'ME', label: 'Maine' , color: '#FF5630'},
    { value: 'MH', label: 'Marshall Islands',color: '#fa26a0' },
    { value: 'MD', label: 'Maryland' , color: '#FF5630'},
    { value: 'MA', label: 'Massachusetts' , color: '#FF5630'},
    { value: 'MI', label: 'Michigan' , color: '#FF5630'},
    { value: 'MN', label: 'Minnesota', color: '#FF5630' },
    { value: 'MS', label: 'Mississippi',color: '#00875A' },
    { value: 'MO', label: 'Missouri', color: '#FF5630' },
    { value: 'MT', label: 'Montana', color: '#0052CC'},
    { value: 'NE', label: 'Nebraska',color: '#00875A' },
    { value: 'NV', label: 'Nevada' , color: '#6a197d'},
    { value: 'NH', label: 'New Hampshire',color: '#45046a'},
    { value: 'NJ', label: 'New Jersey' , color: '#1dd3bd'},
    { value: 'NM', label: 'New Mexico', color: '#6a197d' },
    { value: 'NY', label: 'New York' , color: '#FF5630'},
    { value: 'NC', label: 'North Carolina',color: '#45046a' },
    { value: 'ND', label: 'North Dakota', color: '#FF5630' },
    { value: 'MP', label: 'Northern Mariana Islands', color: '#FF5630' },
    { value: 'OH', label: 'Ohio' , color: '#FF5630'},
    { value: 'OK', label: 'Oklahoma', color: '#0052CC' },
    { value: 'OR', label: 'Oregon' , color: '#FF5630'},
    { value: 'PW', label: 'Palau' , color: '#FF5630'},
    { value: 'PA', label: 'Pennsylvania' , color: '#1dd3bd'},
    { value: 'PR', label: 'Puerto Rico' , color: '#FF5630'},
    { value: 'RI', label: 'Rhode Island',color: '#00875A' },
    { value: 'SC', label: 'South Carolina' , color: '#6a197d'},
    { value: 'SD', label: 'South Dakota' ,color: '#00875A'},
    { value: 'TN', label: 'Tennessee', color: '#0052CC'},
    { value: 'TX', label: 'Texas' ,color: '#00875A'},
    { value: 'UT', label: 'Utah' ,color: '#00875A'},
    { value: 'VT', label: 'Vermont' ,color: '#00875A'},
    { value: 'VI', label: 'Virgin Islands',color: '#d9455f' },
    { value: 'VA', label: 'Virginia' ,color: '#00875A'},
    { value: 'WA', label: 'Washington',color: '#1dd3bd' },
    { value: 'WV', label: 'West Virginia' ,color: '#00875A'},
    { value: 'WI', label: 'Wisconsin' ,color: '#00875A'},
    { value: 'WY', label: 'Wyoming' ,color: '#00875A'},
  ];
  
 
  